"""add filename to file_ref

Revision ID: 07516eea5685
Revises: cc58d2b6f7d1
Create Date: 2025-11-11 19:48:06.932811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07516eea5685'
down_revision: Union[str, None] = 'cc58d2b6f7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_ref', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_ref', 'filename')
    # ### end Alembic commands ###
