"""add report_image table

Revision ID: 3f65e4700d4a
Revises: 1db3ebe221f5
Create Date: 2025-11-07 18:17:57.060964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f65e4700d4a"
down_revision: str | None = "1db3ebe221f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_image",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("file_ref_id", sa.UUID(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('TABLE', 'OTHER')", name="report_image_kind_check"),
        sa.CheckConstraint("order_index >= 0", name="report_image_order_check"),
        sa.CheckConstraint("page >= 0", name="report_image_page_check"),
        sa.ForeignKeyConstraint(["file_ref_id"], ["file_ref.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["report_id"], ["report.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id", "page", "order_index", name="report_image_order_unique"),
    )
    op.create_index("idx_report_image_report", "report_image", ["report_id"], unique=False)
    op.alter_column(
        "extracted_metric",
        "source",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "file_ref",
        "storage",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("metric_def_code_unique", "metric_def", type_="unique")
    op.drop_constraint("prof_activity_code_unique", "prof_activity", type_="unique")
    op.alter_column(
        "report",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint("user_email_unique", "user", type_="unique")
    op.drop_index("idx_weight_table_prof_activity", table_name="weight_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_weight_table_prof_activity", "weight_table", ["prof_activity_id"], unique=False
    )
    op.create_unique_constraint(
        "user_email_unique", "user", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "user",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'PENDING'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'USER'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "report",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'UPLOADED'::character varying"),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        "prof_activity_code_unique", "prof_activity", ["code"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        "metric_def_code_unique", "metric_def", ["code"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "file_ref",
        "storage",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'LOCAL'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "extracted_metric",
        "source",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'OCR'::character varying"),
        existing_nullable=False,
    )
    op.drop_index("idx_report_image_report", table_name="report_image")
    op.drop_table("report_image")
    # ### end Alembic commands ###
