"""remove report type field and constraints

Revision ID: cc58d2b6f7d1
Revises: 174f323110bc
Create Date: 2025-11-11 19:10:00.912479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc58d2b6f7d1'
down_revision: Union[str, None] = '174f323110bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint for report type
    op.drop_constraint('report_type_check', 'report', type_='check')
    # Drop UNIQUE constraint on participant_id + type
    op.drop_constraint('report_participant_type_unique', 'report', type_='unique')
    # Drop type column
    op.drop_column('report', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore type column
    op.add_column('report', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # Restore UNIQUE constraint on participant_id + type
    op.create_unique_constraint('report_participant_type_unique', 'report', ['participant_id', 'type'], postgresql_nulls_not_distinct=False)
    # Restore CHECK constraint for report type
    op.create_check_constraint('report_type_check', 'report', "type IN ('REPORT_1', 'REPORT_2', 'REPORT_3')")
    # ### end Alembic commands ###
